SFX_BULLET_FIRE = love.audio.newSource("Sound/bulletFire.wav", "static")
SFX_ENEMY_HIT = love.audio.newSource("Sound/enemyHit.wav", "static")
SFX_SPAWNER_HIT = love.audio.newSource("Sound/spawnerHit.wav", "static")
SFX_DOOR_UNLOCK = love.audio.newSource("Sound/doorUnlock.wav", "static")
SFX_KEY_PICKUP = love.audio.newSource("Sound/keyPickup.wav", "static")
SFX_HEALTH_PICKUP = love.audio.newSource("Sound/healthPickup.wav", "static")
SFX_POISON_PICKUP = love.audio.newSource("Sound/poisonPickup.wav", "static")
SFX_LEVEL_PROGRESS = love.audio.newSource("Sound/levelProgress.wav", "static")